spring.application.name=kursova
spring.datasource.url=jdbc:postgresql://localhost:5432/fishingProject
spring.datasource.username=postgres
spring.datasource.password=0751
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

server.servlet.session.timeout=604800s
server.servlet.session.cookie.max-age=604800s

